# -------- WIP / DO NOT USE --------
version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev